// Sample data for development and fallback purposes
export const sampleDashboardStats = {
  totalBuildings: 5,
  totalUnits: 24,
  vacantUnits: 8,
  occupiedUnits: 16,
  totalTenants: 16,
  pendingInquiries: 3,
  monthlyRevenue: 480000,
  occupancyRate: 66.7,
  revenueChange: 12.5,
  inquiriesChange: -2.1,
  recent_inquiries: [
    {
      id: "1",
      name: "John Smith",
      subject: "Inquiry about 2BR apartment",
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "2",
      name: "Mary Johnson",
      subject: "Property viewing request",
      created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "3",
      name: "David Wilson",
      subject: "Commercial space inquiry",
      created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
  ],
  recent_notices: [
    {
      id: "1",
      title: "Building Maintenance Schedule",
      type: "maintenance",
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "2",
      title: "Community BBQ Event",
      type: "event",
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
}

export const sampleVacantUnits = [
  {
    id: "1",
    title: "Modern 2BR Apartment in Westlands",
    description: "Beautiful modern apartment with great amenities",
    property_type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    square_feet: 1200,
    rent_amount: 45000,
    selling_price: null,
    deposit_amount: 90000,
    address: "Westlands Road",
    city: "Nairobi",
    state: "Nairobi",
    amenities: ["parking", "gym", "pool"],
    images: ["/placeholder.svg?height=300&width=400"],
    status: "available",
    featured: true,
    available_from: new Date().toISOString(),
    frequency: 1,
    category: "for rent",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    contact_info: "agent@example.com",
    viewing_fee: 1000,
  },
  {
    id: "2",
    title: "Luxury 3BR House in Karen",
    description: "Spacious family home in quiet neighborhood",
    property_type: "house",
    bedrooms: 3,
    bathrooms: 3,
    square_feet: 2500,
    rent_amount: null,
    selling_price: 8500000,
    deposit_amount: null,
    address: "Karen Road",
    city: "Nairobi",
    state: "Nairobi",
    amenities: ["garden", "garage", "security"],
    images: ["/placeholder.svg?height=300&width=400"],
    status: "available",
    featured: false,
    available_from: new Date().toISOString(),
    frequency: 1,
    category: "for sale",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    contact_info: "agent@example.com",
    viewing_fee: 2000,
  },
  {
    id: "3",
    title: "Studio Apartment in CBD",
    description: "Perfect for young professionals",
    property_type: "studio",
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 600,
    rent_amount: 25000,
    selling_price: null,
    deposit_amount: 50000,
    address: "Kenyatta Avenue",
    city: "Nairobi",
    state: "Nairobi",
    amenities: ["wifi", "security"],
    images: ["/placeholder.svg?height=300&width=400"],
    status: "available",
    featured: false,
    available_from: new Date().toISOString(),
    frequency: 3,
    category: "for rent",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    contact_info: "agent@example.com",
    viewing_fee: 500,
  },
  {
    id: "4",
    title: "Commercial Office Space",
    description: "Prime location for business",
    property_type: "commercial",
    bedrooms: 0,
    bathrooms: 2,
    square_feet: 1500,
    rent_amount: 80000,
    selling_price: null,
    deposit_amount: 160000,
    address: "Moi Avenue",
    city: "Nairobi",
    state: "Nairobi",
    amenities: ["parking", "elevator", "security"],
    images: ["/placeholder.svg?height=300&width=400"],
    status: "available",
    featured: true,
    available_from: new Date().toISOString(),
    frequency: 1,
    category: "for rent",
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    contact_info: "agent@example.com",
    viewing_fee: 3000,
  },
]

export const sampleInquiries = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+254712345678",
    subject: "Inquiry about 2BR apartment",
    message:
      "Hi, I am interested in renting a 2-bedroom apartment in Westlands. Could you please provide more details about availability and pricing?",
    status: "new" as const,
    priority: "high" as const,
    property_interest: "2BR Apartment in Westlands",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    name: "Mary Johnson",
    email: "mary.johnson@email.com",
    phone: "+254723456789",
    subject: "Property viewing request",
    message: "I would like to schedule a viewing for the 3-bedroom house in Karen. When would be a good time?",
    status: "in-progress" as const,
    priority: "medium" as const,
    property_interest: "3BR House in Karen",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    name: "David Wilson",
    email: "david.wilson@email.com",
    subject: "Commercial space inquiry",
    message: "Looking for office space in the CBD area. What options do you have available?",
    status: "new" as const,
    priority: "medium" as const,
    property_interest: "Office Space in CBD",
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    name: "Sarah Brown",
    email: "sarah.brown@email.com",
    phone: "+254734567890",
    subject: "Maintenance request",
    message: "The air conditioning in my apartment is not working properly. Could someone come and check it?",
    status: "resolved" as const,
    priority: "high" as const,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    name: "Michael Davis",
    email: "michael.davis@email.com",
    phone: "+254745678901",
    subject: "Lease renewal inquiry",
    message: "My lease is expiring next month. I would like to discuss renewal options.",
    status: "in-progress" as const,
    priority: "low" as const,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
]

export const sampleNotices = [
  {
    id: "1",
    title: "Building Maintenance Schedule",
    content:
      "Dear residents, we will be conducting routine maintenance on the elevators this weekend from 9 AM to 5 PM. Please use the stairs during this time. We apologize for any inconvenience.",
    type: "maintenance" as const,
    priority: "high" as const,
    status: "published" as const,
    target_audience: "tenants" as const,
    published_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Community BBQ Event",
    content:
      "Join us for our monthly community BBQ this Saturday at 6 PM in the courtyard. Food and drinks will be provided. Please RSVP by Thursday.",
    type: "event" as const,
    priority: "medium" as const,
    status: "published" as const,
    target_audience: "all" as const,
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "Water Supply Interruption",
    content:
      "Due to emergency repairs, water supply will be interrupted tomorrow from 10 AM to 2 PM. Please store water in advance. Emergency contact: +254700000000",
    type: "emergency" as const,
    priority: "high" as const,
    status: "published" as const,
    target_audience: "tenants" as const,
    published_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "New Parking Regulations",
    content:
      "Starting next month, new parking regulations will be in effect. All vehicles must display valid parking permits. Permits can be obtained from the management office.",
    type: "general" as const,
    priority: "medium" as const,
    status: "draft" as const,
    target_audience: "all" as const,
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    title: "Holiday Office Hours",
    content:
      "Please note that the management office will have reduced hours during the holiday season. We will be open from 9 AM to 3 PM on weekdays only.",
    type: "general" as const,
    priority: "low" as const,
    status: "published" as const,
    target_audience: "all" as const,
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
